### ISSUE TITLE
javadoc build fails

### ISSUE THREAD

**Issue by mkmik** [thepaul/libjna-java#1]
when I try to build the package it fails because javadoc fails

 [javadoc] Constructing Javadoc information...
  [javadoc] /home/marko/Build/libjna-java/contrib/platform/src/com/sun/jna/platform/KeyboardUtils.java:19: cannot find symbol
  [javadoc] symbol  : class Platform
  [javadoc] location: package com.sun.jna
  [javadoc] import com.sun.jna.Platform;

**Comment by thepaul** [comment]
How are you doing the build, and on what distro/suite?  It works for me in a clean pbuilder with git-buildpackage on lenny+bpo, squeeze, and sid.

**Comment by mkmik** [comment]
ubuntu 10.04, building with 'debuild' on a git checkout, no pbuilder. Sorry I'm a novice to deb packaging. I thought that pbuilder was to ensure that the packager didn't forget to declare some build deps. How should I build the package?

(Btw, I need it because I read somewhere that cassandra 0.6.x needs this version, as it doesn't work with the version shipped in ubuntu 10.04)

**Comment by thepaul** [comment]
Aha, git-buildpackage was taking care of quilt patches automatically, where debuild wasn't.  Fixed, I think- try it now.

**Comment by mkmik** [comment]
thank you, it worked!
